### ISSUE TITLE
V5 Roadmap

### ISSUE THREAD

**Issue by pionxzh** [TexteaInc/json-viewer#515]
V4 would be the last version with MUI.
I want to make the following changes in the next major version.

- [ ] Remove MUI to reduce the package size
- [ ] Fully support Next.js 14 and SSR issues.\
SSR is not working properly because of MUI and how our internal store is implemented.\
#429
    - [ ] Refactor the internal store
- [ ] Improve the performance of hovering on deep nested data.\
#470
